---
- name: Prerequestion
  hosts: all
  become: yes 
  tasks:
    
  - name: set timezone
    timezone:
      name: Europe/Moscow
  
  - name: "Build hosts file"
    lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_host }} {{item}}" state=present
    when: hostvars[item].ansible_default_ipv4.address is defined
    with_items: "{{ groups['all'] }}"

  - name: Disable SELinux
    selinux:
      state: disabled
    register: selinux_status

  - name: Reboot host
    reboot:
      reboot_timeout: 3600
    when: selinux_status is changed

- name: Set database
  hosts: databases
  become: True
  roles:
    - etcd
    - patroni

- name: Set haproxy for patroni
  hosts: hpx
  become: True  
  roles:
    - haproxy
    
