# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "generic/alma9"
    #config.vm.box = "generic/centos7" #image with lvm
 
    config.vm.provider "virtualbox" do |v|
      v.cpus=1
      v.memory=512
    end

    config.vm.define "pcn1" do |pcx1|
      pcx1.vm.hostname = "pcn1"      
      pcx1.vm.network "private_network", ip: "192.168.56.30"
    end

    config.vm.define "pcn2" do |pcx2|
      pcx2.vm.hostname = "pcn2"      
      pcx2.vm.network "private_network", ip: "192.168.56.31"
    end


    config.vm.define "pcn3" do |pcx3|
      pcx3.vm.hostname = "pcn3"      
      pcx3.vm.network "private_network", ip: "192.168.56.32"
    end

    config.vm.define "haproxy" do |hapx|
      hapx.vm.hostname = "haproxy"      
      hapx.vm.network "private_network", ip: "192.168.56.50"
    end
end