---
# tasks file for vector
- name: Install Vector
  dnf:
    name: "{{ rpm_url }}"
    state: present
    disable_gpg_check: true

- name: set config vector for backend
  template:
    src: vector_backend.yaml
    dest: /etc/vector/vector.yaml
  when: inventory_hostname in groups['backends']

- name: set config vector for kafka
  template:
    src: vector_kafka.yaml
    dest: /etc/vector/vector.yaml
  when: " 'kafka' in group_names " 

- name: Start and enable vector
  service:
    name: vector
    state: started
    enabled: true

