---
# tasks file for iscsi
# - name: Generate /etc/hosts file
#   template:
#     src=hosts.j2
#     dest=/etc/hosts

- blockinfile:
    path: /etc/hosts
    marker: "{mark} {{ item }}"
    block: |
      {% for iface in ['eth1', 'eth2'] if iface in hostvars[item].ansible_interfaces %}
      {{ hostvars[item]['ansible_%s' % iface].ipv4.address }} {{ item }} {{ item }}-{{iface}}
      {% endfor %}
  loop: "{{ groups.all }}"

- name: Set target
  include_tasks: target.yml
  when: inventory_hostname in groups[ "targets" ] 

- name: Set clients
  include_tasks: client.yml
  when: inventory_hostname in groups[ "clients" ]
