---
- name: Prerequestion
  hosts: all
  remote_user: "{{ remote_user }}"
  become: yes 

  tasks:
    
  - name: set timezone
    timezone:
      name: Europe/Moscow
  
  - name: set hosts file
    template:
      src: templates/hosts
      dest: /etc/hosts

  - name: Disable SELinux
    selinux:
      state: disabled
    register: selinux_status

  - name: Reboot host
    reboot:
      reboot_timeout: 3600
    when: selinux_status is changed
  
- name: Set database for wordpress
  hosts:
    - databases
  become: True
  remote_user: "{{ remote_user }}"
  roles:
    - database

- name: Set backend
  hosts:
    - backends
  become: True
  remote_user: "{{ remote_user }}"
  roles:
    - nginx
    - php
    - wordpress

- name: Deploy consul
  hosts: all
  become: true
  remote_user: "{{ remote_user }}"
  roles:
    - consul
  
- name: Set balancer
  hosts:
    - balancers
  become: true
  remote_user: "{{ remote_user }}"
  roles:
    - nginx_consul




  

