---
# tasks file for balancer
- name: Install NGINX
  yum: 
    name: nginx 
    state: present
    update_cache: true

- name: set nginx config
  template:
    src: balancer.conf.j2
    dest: /etc/nginx/conf.d/api.conf

- name: start NGINX
  service:
    name: nginx 
    state: restarted
    enabled: true

