
cluster.name: "{{ cluster_name }}"

node.name: "{{ inventory_hostname }}"

network.host: "{{ hostvars[inventory_hostname]['ansible_eth0'].ipv4.address }}"

http.port: 9200

bootstrap.memory_lock: true

discovery.seed_hosts:  ["{{ os_nodes }}"]
cluster.initial_master_nodes: ["{{ os_master_nodes }}"]

node.roles: {% if inventory_hostname == 'ops1' %} [ data, master] {% else %} [ data,ingest] {% endif %}
## END opensearch main configuration ##
## BEGIN OpenSearch Security common configuration ##
plugins.security.disabled: false
plugins.security.allow_unsafe_democertificates: false #

