---
- name: Prerequestion
  hosts: all
  remote_user: "{{ remote_user }}"
  become: yes 

  tasks:
    
  - name: set timezone
    timezone:
      name: Europe/Moscow
  
  - name: set hosts file
    template:
      src: templates/hosts
      dest: /etc/hosts

  - name: Disable SELinux
    selinux:
      state: disabled
    register: selinux_status

  - name: Reboot host
    reboot:
      reboot_timeout: 3600
    when: selinux_status is changed


- name: Install database cluster
  hosts: database
  become: True
  remote_user: "{{ remote_user }}"
  roles:
   - pxc

- name: Set up iscsi
  hosts:
    - backends
    - targets
  become: true
  remote_user: "{{ remote_user }}"
  roles:
    - { role: 'OndrejHome.targetcli-modules'}
    - iscsi

- name: Set backend
  hosts: backends
  become: true
  remote_user: "{{ remote_user }}"
  roles: 
    - pacemaker
    - fence 
    - gfs2
    - nginx
    - php
    - wordpress

- name: Deploy opensearch
  hosts:
    - elk
  become: True
  remote_user: "{{ remote_user }}"
  roles:
    - opensearch
    - dashboard

- name: Deploy consul
  hosts: all
  become: true
  remote_user: "{{ remote_user }}"
  roles:
    - consul

- name: Deploy dnsmasq
  hosts: consul
  become: true
  remote_user: "{{ remote_user }}"
  roles:
    - dnsmasq

- name: Postconfig
  hosts: all
  remote_user: "{{ remote_user }}"
  become: yes 

  tasks:

  - name: read default resolve.conf
    shell: "cat /etc/resolv.conf"
    register: resolv
  
  - name: set resolv.conf
    template:
      src: resolv.conf
      dest: /etc/resolv.conf

- name: Deploy balancer
  hosts: balancer
  become: True
  remote_user: "{{remote_user}}"
  roles:
    - balancer

- name: Deploy vector
  hosts: backends
  become: true
  remote_user: "{{ remote_user }}"
  roles: 
    - vector



  

