---

# include_roles: { role: 'OndrejHome.targetcli' }
# - name: Add port 3260 ot firewall
#   firewalld:
#     port: 3260/tcp
#     permanent: True
#     state: enabled
#   register: add_port

# - name: reload firewalld
#   service:
#     name: firewalld
#     state: reloaded
#   when: add_port is changed


- name: Install extension and utilites
  yum:
    name: targetcli
    state: present
    update_cache: yes

- name: Start and enable targetcli service
  service:
    name: target
    enabled: True
    state: started

- name: Create backstore
  targetcli_backstore:
    backstore_type: "{{ item.1.type }}"
    backstore_name: "{{ item.1.name }}"
    options: "{{ item.1.path }}"
  with_subelements:
    - "{{ iscsi_targets }}"
    - disks
  notify:
    - save targetcli configuration

- name: create iSCSI targets
  targetcli_iscsi:
    wwn: "{{ item.name }}"
  with_items: "{{ iscsi_targets }}"
  notify:
    - save targetcli configuration

- name: assing LUNs to initiators
  targetcli_iscsi_lun:
    wwn: "{{ item.0.name }}"
    backstore_type: "{{ item.1.type }}"
    backstore_name: "{{ item.1.name }}"
  with_subelements:
    - "{{ iscsi_targets }}"
    - disks
  notify:
    - save targetcli configuration

- name: define ACLs for iSCSI target
  targetcli_iscsi_acl:
    wwn: "{{ item.0.name }}"
    initiator_wwn: "{{ item.1.name }}"
  with_subelements:
    - "{{ iscsi_targets }}"
    - initiators
  notify:
    - save targetcli configuration