---
- name: Prerequestion
  hosts: all
  remote_user: "{{ remote_user }}"
  become: yes 

  tasks:
    
  - name: set timezone
    timezone:
      name: Europe/Moscow
  
  - name: set hosts file
    template:
      src: templates/hosts
      dest: /etc/hosts

  - name: Disable SELinux
    selinux:
      state: disabled
    register: selinux_status

  - name: Reboot host
    reboot:
      reboot_timeout: 3600
    when: selinux_status is changed
  
- name: Set opensearch app
  hosts:
    - elk
  become: True
  remote_user: "{{ remote_user }}"
  roles:
    - opensearch

- name: Set opensearch app
  hosts:
    - master
  become: True
  remote_user: "{{ remote_user }}"
  roles:
    - dashboard
    - vector



  

