---
- name: Prerequestion
  hosts: all
  remote_user: "{{ remote_user }}"
  become: yes 

  tasks:
    
  - name: set timezone
    timezone:
      name: Europe/Moscow
  
  # - name: "Build hosts file"
  #   lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_host }} {{item}}" state=present
  #   when: hostvars[item].ansible_default_ipv4.address is defined
  #   with_items: "{{ groups['all'] }}"

  - name: set hosts file
    template:
      src: templates/hosts
      dest: /etc/hosts

  - name: Disable SELinux
    selinux:
      state: disabled
    register: selinux_status

  - name: Reboot host
    reboot:
      reboot_timeout: 3600
    when: selinux_status is changed
  
- name: Set database
  hosts: databases
  become: True
  remote_user: "{{ remote_user }}"
  roles:
    - database

- name: set up iscsi
  hosts:
    - backend
    - targets
  become: true
  remote_user: "{{ remote_user }}"
  roles:
    - { role: 'OndrejHome.targetcli-modules' }
    - iscsi

- name: Set backend
  hosts: backend
  become: True
  remote_user: "{{ remote_user }}"
  roles:
    - pacemaker
    - fence
    - gfs2
    - nginx
    - php
    - wordpress

  

