---

- name: Download opensearch {{ os_version }}
  get_url:
    url: "{{ os_download_url }}/{{ os_version }}/opensearch-{{ os_version }}-linux-x64.tar.gz"
    dest: "/tmp/opensearch.tar.gz"
  register: download

- name: Create opensearch user
  user:
    name: "{{ os_user }}"
    state: present
    shell: /bin/false
    create_home: true
    home: "{{ os_home }}"
  when: download.changed

- name: Create home directory
  file:
    path: "{{ os_home }}"
    state: directory
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
  when: download.changed


- name: Extract the tar file
  unarchive:
    src: /tmp/opensearch.tar.gz
    dest: "{{ os_home }}"
    remote_src: yes
    extra_opts: --strip-components=1
  when: download.changed

# - name: Copy Configuration File
#   blockinfile:
#     block: "{{ lookup('template', 'templates/opensearch-{{ cluster_type }}.yml') }}"
#     dest: "{{ os_conf_dir }}/opensearch.yml"
#     backup: true
#     state: present
#     create: true
#     marker: "## {mark} opensearch main configuration ##"
#     owner: "{{ os_user }}"
#     group: "{{ os_user }}"
#     mode: 0600

- name: Copy configuration file
  template:
    src: opensearch.yml
    dest: "{{os_conf_dir }}/opensearch.yml"
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    mode: 0600
  # when: download.changed


- name: Copy jvm.options File for Instance
  template:
    src: jvm.options
    dest: "{{ os_conf_dir }}/jvm.options"
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    mode: 0600
    force: true

- name: create systemd service
  template:
    src: opensearch.service
    dest: "{{ systemctl_path }}/opensearch.service"