---
- name: Prerequestion
  hosts: all
  become: yes 
  tasks:
    
  - name: set timezone
    timezone:
      name: Europe/Moscow
  
  - name: "Build hosts file"
    lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_host }} {{item}}" state=present
    when: hostvars[item].ansible_default_ipv4.address is defined
    with_items: "{{ groups['all'] }}"

  - name: Disable SELinux
    selinux:
      state: disabled
    register: selinux_status

  - name: Reboot host
    reboot:
      reboot_timeout: 3600
    when: selinux_status is changed

  - name: Add firewalld rules (TCP)
    firewalld:
      port: "{{item}}/tcp"
      state: enabled
      permanent: true
    with_items:
      - 4505
      - 4506
    register: firewalld_state

  - name: reload firewalld
    service:
      name: firewalld
      state: reloaded
    when: firewalld_state is changed

- name: Set backend
  hosts: backends
  become: True
  roles:
    - php
    - wordpress
    - database

- name: Deploy Salt
  hosts: salt, minion
  become: true
  roles:
    - salt


