---
- name: Prerequestion
  hosts: all
  become: yes 
  remote_user: centos
  tasks:
    
  - name: Install epel repo
    yum:
      name: epel-release
      state: present
      update_cache: yes

  - name: set timezone
    timezone:
      name: Europe/Moscow
  
  - name: "Build hosts file"
    lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_host }} {{item}}" state=present
    when: hostvars[item].ansible_default_ipv4.address is defined
    with_items: "{{ groups['all'] }}"

  - name: Disable SELinux
    selinux:
      state: disabled
    register: selinux_status

  - name: Reboot host
    reboot:
      reboot_timeout: 3600
    when: selinux_status is changed

- name: Set database
  hosts: databases
  become: True
  remote_user: centos
  roles:
    - database

- name: Set backend
  hosts: backend
  become: True
  remote_user: centos
  roles:
    - nginx
    - php
    - wordpress
  
- name: Install balancer
  hosts: balancers
  become: True
  remote_user: centos
  roles:
    - balancer

  

  

